export {
  fetchAllRanges,
  fetchAllRangesAbsolute,
  fetchCurrent,
  fetchDailyScores,
  fetchRange,
  fetchRangeAbsolute,
  fetchRangeRaw,
  toDateStr,
  type CurrentMetric,
  type CurrentResponse,
  type DailyScore,
  type RangePoint,
  type RangeResponse,
} from "../shared/api/backendClient";
